/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Combo: typeof import('./src/components/Combo.vue')['default']
    DocDialog: typeof import('./src/components/DocDialog.vue')['default']
    RecordList: typeof import('./src/components/RecordList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StockTree: typeof import('./src/components/StockTree.vue')['default']
  }
}
